server:
  port: 8081
  servlet:
    path: /

org:
  defined:
    swagger2Enabled: false
    shortMessageEnabled: true
    bucket: d1fined-case-test
    uri: http://d1fined-case-test.oss-cn-hangzhou.aliyuncs.com/

mybatis-plus:
  global-config:
    refresh: true

spring:
  datasource:
    url: jdbc:mysql://101.132.116.108:3306/first_see_test
    username: jixiao
    password: U2FsdGVkX1/kI8gTEbiDwpdHxVl0Jf4+3lzKJr+kdCAYhTLEIqs=
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      poolName: DiyDataSource
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      data-source-properties:
        characterEncoding: utf-8
        useUnicode: true
        useSSL: false
        autoReconnect: true
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  redis:
    database: 7
    host: 101.132.116.108
    password: dJB9ZYDIM6ZA4dNZEc4Tqwtrp4Zq7Tey4TMK2DCp752npJTXoNxXy2ANpPG6HjVO
    jedis:
      pool:
        max-active: 32
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    port: 6379
    timeout: 2000ms